name: galerimusik_klpk7
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  dio: ^4.0.6
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  flare_flutter: ^3.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  theme_provider: ^0.5.0
  lottie: ^1.2.2
  url_launcher: ^6.1.0
  cached_network_image: ^3.2.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo-signin.png
    - assets/flare_animations/
    - assets/lottie_animations/

  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
